services:
  my_zhi_hu_api:
    image: my_zhi_hu_api
    container_name: my_zhi_hu_api
    user: root
    restart: always
    ports:
      - 8080:8080
    environment:
      - ASPNETCORE_ENVIRONMENT=Development
      - ASPNETCORE_URLS=https://+:8000
      - ASPNETCORE_Kestrel__Certificates__Default__Password=abc123
      - ASPNETCORE_Kestrel__Certificates__Default__Path=/https/aspnetapp.pfx
    volumes:
      - ./MyZhiHuAPI/Config/aspnetapp.pfx:/https/aspnetapp.pfx
    build:
      context: .
      dockerfile: MyZhiHuAPI/Dockerfile
